/my-portfolio
|-- /css
|   |-- styles.css
|-- /js
|   |-- scripts.js
|-- /images
|   |-- logo.png
|   |-- hero-bg.jpg
|-- /pages
|   |-- about.html
|   |-- projects.html
|   |-- publications.html
|   |-- contact.html
|-- index.html
|-- README.md
